#! /usr/bin/osascript
on run argv
set theFile to POSIX file (item 1 of argv) as alias
tell application "Skim"
  activate
  set theDocs to get documents whose path is (get POSIX path of theFile)
  if (count of theDocs) > 0 then revert theDocs
  open theFile
end tell
end run

